
import streamlit as st
import json
from datetime import datetime
from pathlib import Path

st.set_page_config(page_title="AI-Made To-Do", page_icon="✅", layout="centered")

DATA_FILE = Path("todos.json")

def load_data():
    if DATA_FILE.exists():
        try:
            return json.loads(DATA_FILE.read_text())
        except Exception:
            return []
    return []

def save_data(items):
    DATA_FILE.write_text(json.dumps(items, indent=2))

def add_item(text, priority, due):
    items = load_data()
    items.append({
        "text": text.strip(),
        "priority": priority,
        "due": due.isoformat() if due else None,
        "done": False,
        "created_at": datetime.utcnow().isoformat()
    })
    save_data(items)

def toggle_done(idx, value):
    items = load_data()
    items[idx]["done"] = value
    save_data(items)

def delete_item(idx):
    items = load_data()
    items.pop(idx)
    save_data(items)

def edit_item(idx, text, priority, due):
    items = load_data()
    items[idx]["text"] = text
    items[idx]["priority"] = priority
    items[idx]["due"] = due.isoformat() if due else None
    save_data(items)

st.title("✅ To‑Do List (Built with AI)")
st.caption("A minimal to‑do app generated by ChatGPT.")

with st.expander("➕ Add a new task", expanded=True):
    col1, col2 = st.columns([3,1])
    with col1:
        new_text = st.text_input("Task", placeholder="What do you need to get done?")
    with col2:
        priority = st.selectbox("Priority", ["Low", "Medium", "High"], index=1)
    due = st.date_input("Due date (optional)", value=None, format="DD/MM/YYYY")
    if st.button("Add task", use_container_width=True, disabled=not new_text.strip() if new_text else True):
        add_item(new_text, priority, due)
        st.success("Task added!")
        st.experimental_rerun()

items = load_data()

# Filters
st.subheader("Your tasks")
f1, f2 = st.columns(2)
with f1:
    status_filter = st.radio("Status", ["All", "Open", "Done"], horizontal=True)
with f2:
    sort_by = st.selectbox("Sort by", ["Created time", "Priority", "Due date"])

# Sorting
priority_order = {"High": 0, "Medium": 1, "Low": 2}
def sort_key(it):
    if sort_by == "Priority":
        return priority_order.get(it["priority"], 99)
    if sort_by == "Due date":
        return (it["due"] is None, it["due"])
    return it["created_at"]

items = sorted(items, key=sort_key)

if status_filter != "All":
    want_done = (status_filter == "Done")
    items = [it for it in items if it["done"] == want_done]

if not items:
    st.info("No tasks yet. Add one above!")
else:
    for idx, it in enumerate(items):
        with st.container():
            cols = st.columns([0.6, 4, 1.2, 1.2, 1])
            with cols[0]:
                done = st.checkbox("Done", value=it["done"], key=f"done_{idx}")
                if done != it["done"]:
                    toggle_done(idx, done)
                    st.experimental_rerun()
            with cols[1]:
                st.write(f"**{it['text']}**")
                meta = []
                if it["priority"]:
                    meta.append(f"Priority: {it['priority']}")
                if it["due"]:
                    try:
                        d = datetime.fromisoformat(it["due"]).date().strftime("%d %b %Y")
                        meta.append(f"Due: {d}")
                    except Exception:
                        pass
                st.caption(" · ".join(meta) if meta else "No metadata")
            with cols[2]:
                if st.button("✏️ Edit", key=f"edit_{idx}"):
                    st.session_state[f"editing_{idx}"] = True
            with cols[3]:
                if st.button("🗑️ Delete", key=f"del_{idx}"):
                    delete_item(idx)
                    st.experimental_rerun()
            with cols[4]:
                pass

            if st.session_state.get(f"editing_{idx}"):
                st.markdown("---")
                etext = st.text_input("Edit text", value=it["text"], key=f"etext_{idx}")
                eprio = st.selectbox("Edit priority", ["Low", "Medium", "High"], index=["Low","Medium","High"].index(it["priority"]), key=f"eprio_{idx}")
                edue = st.date_input("Edit due date", value=(datetime.fromisoformat(it["due"]).date() if it["due"] else None), key=f"edue_{idx}", format="DD/MM/YYYY")
                save, cancel = st.columns(2)
                with save:
                    if st.button("Save", key=f"save_{idx}"):
                        edit_item(idx, etext, eprio, edue)
                        st.session_state[f"editing_{idx}"] = False
                        st.experimental_rerun()
                with cancel:
                    if st.button("Cancel", key=f"cancel_{idx}"):
                        st.session_state[f"editing_{idx}"] = False
                        st.experimental_rerun()

st.markdown("---")
st.caption("Tip: This app stores tasks in a local **todos.json** file on the server. Deploy to Streamlit Cloud or Hugging Face Spaces to get a public URL.")
